FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY backend/main.py ./main.py
COPY backend/api ./api
RUN ls -l /app
EXPOSE 8081
CMD ["bash", "-c", "uvicorn main:app --host 0.0.0.0 --port 8081"] 