version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3001:80"
    environment:
      - REACT_APP_API_URL=http://0.0.0.0:8081
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    networks:
      - app-network
    depends_on:
      - python-api-proxy

  python-api-proxy:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8081:8081"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 