version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://10.0.6.178:8088
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 